name: Auto Label PRs

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
      - staging

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add 'run-bittensor-sdk-tests' label to PR
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: run-bittensor-sdk-tests
