name: Add Labels to PR

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'staging' || github.event.pull_request.base.ref == 'main'
    steps:
      - name: Add labels to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: run-bittensor-sdk-tests, run-bittensor-cli-tests
