name: Bittensor Checks

concurrency:
  group: e2e-sdk-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - staging
    types: [opened, synchronize, reopened, labeled, unlabeled]

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.event.inputs.verbose }}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    outputs:
      skip-tests: ${{ contains(github.event.pull_request.labels.*.name, 'skip-bittensor-tests') }}
      run-sdk-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-sdk-tests') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

  find-e2e-tests:
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.get-tests.outputs.test-files }}
    steps:
      - name: Research preparation
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/bittensor.git

      - name: Checkout
        working-directory: ${{ github.workspace }}/bittensor
        run: git checkout staging

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Find e2e test files
        id: get-tests
        run: |
          test_files=$(find ${{ github.workspace }}/bittensor/tests/e2e_tests -name "test*.py" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "::set-output name=test-files::$test_files"
        shell: bash

  cache-nodes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clone Subtensor repo
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/subtensor.git

      - name: Checkout Subtensor repo to `devnet-ready` branch
        working-directory: ${{ github.workspace }}/subtensor
        run: git checkout devnet-ready

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler jq

      - name: Add wasm32-unknown-unknown target
        run: |
          rustup target add wasm32-unknown-unknown --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

      - name: Build Subtensor nodes
        run: |
          echo "Bilding fast block nodes"
          ${{ github.workspace }}/subtensor/scripts/localnet.sh --build-only
          echo "Bilding non-fast block nodes"
          ${{ github.workspace }}/subtensor/scripts/localnet.sh False --build-only

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/subtensor/target/
          key: ${{ runner.os }}-subtensor-node

  run-tests:
    needs:
      - check-labels
      - find-e2e-tests
      - cache-nodes
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.draft == false && needs.check-labels.outputs.run-sdk-tests == 'true' }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        rust-branch:
          - stable
        rust-target:
          - x86_64-unknown-linux-gnu
        os:
          - ubuntu-latest
        test-file: ${{ fromJson(needs.find-e2e-tests.outputs.test-files) }}
    timeout-minutes: 60
    name: "Run Tests: ${{ matrix.test-file }}"
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler jq

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal

      - name: Add wasm32-unknown-unknown target
        run: |
          rustup target add wasm32-unknown-unknown --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

      - name: Create Python virtual environment
        working-directory: ${{ github.workspace }}
        run: python3 -m venv venv

      - name: Clone Bittensor SDK repo
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/bittensor.git

      - name: Setup Bittensor SDK from cloned repo
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          git checkout staging
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'
          python3 -m pip install maturin

      - name: Clone Bittensor Wallet repo
        run: git clone https://github.com/opentensor/btwallet.git

      - name: Checkout PR branch in Wallet repo
        working-directory: ${{ github.workspace }}/btwallet
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Build and install Rust Bittensor Wallet package
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          maturin develop

      - name: Run SDK integration tests
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install uv dependencies
        run: uv sync --all-extras --dev

      - name: Clone Subtensor repo
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/subtensor.git

      - name: Checkout Subtensor repo to `devnet-ready` branch
        working-directory: ${{ github.workspace }}/subtensor
        run: git checkout devnet-ready

      - name: Restore cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ github.workspace }}/subtensor/target/
          key: ${{ runner.os }}-subtensor-node

      - name: Run Bittensor SDK e2e test
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          LOCALNET_SH_PATH="${{ github.workspace }}/subtensor/scripts/localnet.sh" uv run pytest ${{ matrix.test-file }} -s
