name: Bittensor BTCLI Test

concurrency:
  group: e2e-cli-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - staging
    types: [opened, synchronize, reopened, labeled, unlabeled]

env:
  CARGO_TERM_COLOR: always
  VERBOSE: ${{ github.event.inputs.verbose }}

jobs:
  check-labels:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false }}
    outputs:
      run-cli-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-cli-tests') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

  find-e2e-tests:
    needs: check-labels
    if: needs.check-labels.outputs.run-cli-tests == 'true'
    runs-on: ubuntu-latest
    outputs:
      test-files: ${{ steps.get-tests.outputs.test-files }}
    steps:
      - name: Research preparation
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/btcli.git

      - name: Checkout
        working-directory: ${{ github.workspace }}/btcli
        run: git checkout staging

      - name: Install dependencies
        run: sudo apt-get install -y jq

      - name: Find e2e test files
        id: get-tests
        run: |
          test_files=$(find ${{ github.workspace }}/btcli/tests/e2e_tests -name "test*.py" | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "::set-output name=test-files::$test_files"
        shell: bash

  pull-docker-image:
    needs: check-labels
    runs-on: ubuntu-latest
    if: needs.check-labels.outputs.run-cli-tests == 'true'
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/opentensor/subtensor-localnet:latest

      - name: Save Docker Image to Cache
        run: docker save -o subtensor-localnet.tar ghcr.io/opentensor/subtensor-localnet:latest

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: subtensor-localnet
          path: subtensor-localnet.tar

  run-e2e-tests:
    needs:
      - check-labels
      - find-e2e-tests
      - pull-docker-image

    if: needs.check-labels.outputs.run-cli-tests == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        rust-branch:
          - stable
        rust-target:
          - x86_64-unknown-linux-gnu
        os:
          - ubuntu-latest
        test-file: ${{ fromJson(needs.find-e2e-tests.outputs.test-files) }}

    env:
      RELEASE_NAME: development
      RUSTV: ${{ matrix.rust-branch }}
      RUST_BACKTRACE: full
      RUST_BIN_DIR: target/${{ matrix.rust-target }}
      TARGET: ${{ matrix.rust-target }}

    timeout-minutes: 60
    name: "e2e tests: ${{ matrix.test-file }}"
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: ${{ matrix.rust-branch }}
          components: rustfmt
          profile: minimal

      - name: Install rust/cargo dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler jq

      - name: Add wasm32-unknown-unknown target
        run: |
          rustup target add wasm32-unknown-unknown --toolchain stable-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create Python virtual environment
        working-directory: ${{ github.workspace }}
        run: uv venv ${{ github.workspace }}/venv

      - name: Clone Bittensor SDK repo
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/btcli.git

      - name: Setup Bittensor-cli from cloned repo
        working-directory: ${{ github.workspace }}/btcli
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          git checkout staging
          uv run --active pip install --upgrade pip
          uv run --active pip install pytest
          uv run --active pip install maturin

      - name: Install uv dependencies
        working-directory: ${{ github.workspace }}
        run: uv sync --all-extras --dev

      - name: Clone Bittensor Wallet repo
        run: git clone https://github.com/opentensor/btwallet.git

      - name: Checkout PR branch in Wallet repo
        working-directory: ${{ github.workspace }}/btwallet
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Build and install Rust Bittensor Wallet package
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          uv run --active maturin develop

      - name: Download Cached Docker Image
        uses: actions/download-artifact@v4
        with:
          name: subtensor-localnet

      - name: Load Docker Image
        run: docker load -i subtensor-localnet.tar

      - name: Run tests
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          uv run pytest ${{ matrix.test-file }} -s


  run-unit-test:
    needs:
      - check-labels
    if: needs.check-labels.outputs.run-cli-tests == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Create Python virtual environment
        working-directory: ${{ github.workspace }}
        run: python3 -m venv venv

      - name: Clone Bittensor SDK repo
        working-directory: ${{ github.workspace }}
        run: git clone https://github.com/opentensor/btcli.git

      - name: Setup Bittensor SDK from cloned repo
        working-directory: ${{ github.workspace }}/btcli
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          git checkout staging
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[dev]'
          python3 -m pip install maturin

      - name: Clone Bittensor Wallet repo
        run: git clone https://github.com/opentensor/btwallet.git

      - name: Checkout PR branch in Wallet repo
        working-directory: ${{ github.workspace }}/btwallet
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Build and install Rust Bittensor Wallet package
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          maturin develop

      - name: Run SDK unit tests
        working-directory: ${{ github.workspace }}
        run: |
          source ${{ github.workspace }}/venv/bin/activate
          pytest ${{ github.workspace }}/btcli/tests/unit_tests