name: PR Checks
on:
  pull_request:
    branches:
      - master
      - staging
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    outputs:
        skip-tests: ${{ contains(github.event.pull_request.labels.*.name, 'skip-bittensor-tests') }}
        run-cli-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-cli-tests') }}
        run-sdk-tests: ${{ contains(github.event.pull_request.labels.*.name, 'run-bittensor-sdk-tests') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

  run-sdk-tests:
    needs: check-labels
    if: needs.check-labels.outputs.run-sdk-tests == 'true'
    runs-on: Bittensor SDK tests
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Check-out repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      - name: Clone bittensor repo
        run: git clone https://github.com/opentensor/bittensor.git

      - name: Setup bittensor repo
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          git checkout staging
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install '.[dev]'
          pip install maturin

      - name: Clone bittensor-wallet repo
        run: git clone https://github.com/opentensor/btwallet.git

      - name: Checkout PR branch
        working-directory: ${{ github.workspace }}/btwallet
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"

      - name: Build and install Rust FFI package into bittensor python env
        working-directory: ${{ github.workspace }}/btwallet
        run: |
          pwd
          source ./../bittensor/venv/bin/activate
          maturin develop

      - name: Run tests
        working-directory: ${{ github.workspace }}/bittensor
        run: |
          source .venv/bin/activate
          LOCALNET_SH_PATH="${{ github.workspace }}/scripts/localnet.sh" pytest tests -s
